### ISSUE TITLE
Emojis Don't Work In Poll Names Or Question Names

### ISSUE THREAD

**Issue by Bradley-B** [Bradley-B/ThimblePolling#4]
The problem here is something about encoding. The database should be currently using utf8mb4, which I think should work.

> DB ERROR:  Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x91\x8C' for column 'name' at row 1
    at Query.Sequence._packetToError (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    --------------------
    at Protocol._enqueue (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\Bradley\WebstormProjects\BetterVoting\server.js:39:5
    at Layer.handle [as handle_request] (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Bradley\WebstormProjects\BetterVoting\node_modules\express\lib\router\index.js:275:10) {
  code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage: "Incorrect string value: '\\xF0\\x9F\\x91\\x8C' for column 'name' at row 1",
  sqlState: 'HY000',
  index: 0,
  sql: "INSERT INTO poll (id, name) VALUES ('v6avZ3MKF2', '❤❤❤👌')"
}

**Comment by Bradley-B** [comment]
Also applies to apostrophes
